---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: .devcontainer
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: components/folderslint
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: components/ftp-client
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: components/mkdocs
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: components/shdoc
    schedule:
      interval: weekly
