---
## Run the defined checks before committing code to the remote repo. This should catch
## simple violations early and lessens the amount of pipeline failures.
##
## Every time you clone a project using pre-commit running `pre-commit install` should always be the
## first thing you do.
##
## IMPORTANT: For pre-commit to work, this file must carry the extension `.yaml`, NOT `.yml`.
##
## == Install the git hook scripts
## run `pre-commit install` to set up the git hook scripts. Now pre-commit will run automatically
## on git commit.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: lint-yaml
        name: lint-yaml
        language: script
        entry: /bin/bash -c 'docker compose up lint-yaml --exit-code-from lint-yaml'
  - repo: local
    hooks:
      - id: lint-workflows
        name: lint-workflows
        language: script
        entry: /bin/bash -c 'docker compose up lint-workflows --exit-code-from lint-workflows'
  - repo: local
    hooks:
      - id: lint-filenames
        name: lint-filenames
        language: script
        entry: /bin/bash -c 'docker compose up lint-filenames --exit-code-from lint-filenames'
  - repo: local
    hooks:
      - id: lint-folders
        name: lint-folders
        language: script
        entry: /bin/bash -c 'docker compose up lint-folders --exit-code-from lint-folders'
  - repo: local
    hooks:
      - id: folderslint-lint-dockerfile
        name: folderslint-lint-dockerfile
        language: script
        entry: /bin/bash -c 'docker compose up folderslint-lint-dockerfile --exit-code-from folderslint-lint-dockerfile'
  - repo: local
    hooks:
      - id: ftp-client-lint-dockerfile
        name: ftp-client-lint-dockerfile
        language: script
        entry: /bin/bash -c 'docker compose up ftp-client-lint-dockerfile --exit-code-from ftp-client-lint-dockerfile'
  - repo: local
    hooks:
      - id: mkdocs-lint-dockerfile
        name: mkdocs-lint-dockerfile
        language: script
        entry: /bin/bash -c 'docker compose up mkdocs-lint-dockerfile --exit-code-from mkdocs-lint-dockerfile'
