---
x-volumes: &volumes
  - /etc/timezone:/etc/timezone:ro
  - /etc/localtime:/etc/localtime:ro
  - project-root-volume:/workspaces/container-images
x-workdir: &default-workdir /workspaces/container-images
x-tty: &tty true

volumes:

  project-root-volume:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind

services:

  lint-yaml:
    image: cytopia/yamllint:latest
    volumes: *volumes
    working_dir: *default-workdir
    command: .
    tty: *tty

  lint-workflows:
    image: rhysd/actionlint:latest
    volumes: *volumes
    working_dir: *default-workdir
    command: -color
    tty: *tty

  lint-filenames:
    image: lslintorg/ls-lint:1.11.2
    volumes: *volumes
    working_dir: *default-workdir
    tty: *tty

  lint-folders:
    image: sommerfeldio/folderslint:latest
    volumes: *volumes
    working_dir: *default-workdir
    command: .
    tty: *tty

  lint-markdown-links:
    image: lycheeverse/lychee:sha-a11d515-alpine
    volumes: *volumes
    working_dir: *default-workdir
    command: --config .lychee.toml .
    tty: *tty

  inspec:
    # template service to run from taskfile.yml
    # not intended to be run directly
    image: &inspec-image chef/inspec:5.22.76
    volumes: *volumes
    working_dir: *default-workdir
    tty: *tty

  docs-build:
    image: &docs-image sommerfeldio/mkdocs:latest
    volumes: *volumes
    working_dir: *default-workdir
    command: build
    tty: *tty

  docs-dev-server:
    image: *docs-image
    volumes: *volumes
    working_dir: *default-workdir
    ports:
      - 3080:8000
    tty: *tty

  devcontainer-lint-dockerfile:
    image: &lint-dockerfile-image hadolint/hadolint:latest
    volumes: *volumes
    working_dir: *default-workdir
    entrypoint: hadolint components/devcontainer/Dockerfile
    tty: *tty

  devcontainer:
    image: local/devcontainer:${DEV_TAG}
    build:
      context: components/devcontainer
      dockerfile: Dockerfile
    tty: *tty

  folderslint-lint-dockerfile:
    image: &lint-dockerfile-image hadolint/hadolint:latest
    volumes: *volumes
    working_dir: *default-workdir
    entrypoint: hadolint components/folderslint/Dockerfile
    tty: *tty

  folderslint:
    image: local/folderslint:${DEV_TAG}
    build:
      context: components/folderslint
      dockerfile: Dockerfile
    volumes: *volumes
    working_dir: *default-workdir
    command: .
    tty: *tty

  ftp-client-lint-dockerfile:
    image: *lint-dockerfile-image
    volumes: *volumes
    working_dir: *default-workdir
    entrypoint: hadolint components/ftp-client/Dockerfile
    tty: *tty

  ftp-client:
    image: local/ftp-client:${DEV_TAG}
    build:
      context: components/ftp-client
      dockerfile: Dockerfile
    tty: *tty

  mkdocs-lint-dockerfile:
    image: *lint-dockerfile-image
    volumes: *volumes
    working_dir: *default-workdir
    entrypoint: hadolint components/mkdocs/Dockerfile
    tty: *tty

  mkdocs:
    image: local/mkdocs:${DEV_TAG}
    build:
      context: components/mkdocs
      dockerfile: Dockerfile
    volumes: *volumes
    working_dir: *default-workdir
    tty: *tty
