---
site_name: Container Images
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  Collection of Container Images for sommerfeld.io projects.

repo_name: sommerfeld-io/container-images
repo_url: https://github.com/sommerfeld-io/container-images

copyright: Copyright &copy; 2024 Sommerfeld.io

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    # - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
  - search:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sommerfeld-io/container-images

nav:
  - Home:
      - index.md
      - Container Images:
          - images/folderslint.md
          - images/ftp-client.md
          - images/mkdocs.md
          - images/shdoc.md
  - About this Project:
      - about/development-guide.md
      - about/project-structure.md
      - about/contribute.md
      - about/security.md
      - about/code-of-conduct.md
      - about/license.md
      - about/terms.md
