---
site_name: Container Images
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  Collection of Container Images for sommerfeld.io projects.

repo_name: sommerfeld-io/container-images
repo_url: https://github.com/sommerfeld-io/container-images

copyright: Copyright &copy; 2024 Sommerfeld.io

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  font:
    text: Work Sans
  palette:
    # scheme: slate
    # primary: blue
    # Palette toggle for light mode
    - scheme: default
      primary: &header-color blue
      accent: *header-color
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: *header-color
      accent: *header-color
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    # - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
  - search:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sommerfeld-io/container-images

nav:
  - Home:
      - index.md
      - license.md
      - Releases on GitHub ⧉: https://github.com/sommerfeld-io/container-images/releases
      - Architecture Decision Records on GitHub ⧉: https://github.com/sommerfeld-io/container-images/issues?q=is%3Aissue+label%3AADR
      - Security Policy ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/security.md
      - How to Contribute ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/contribute.md
      - Code of Conduct ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/code-of-conduct.md
      - Terms of Use ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/terms.md
  - Container Images:
      - images/devcontainer.md
      - images/folderslint.md
      - images/ftp-client.md
      - images/mkdocs.md
