---
version: '3.42.1'

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose up cleanup
      - docker compose down --remove-orphans

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for:
          matrix:
            LINTER: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{.ITEM.LINTER}} --exit-code-from lint-{{.ITEM.LINTER}}

  # ===============================================================================================

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - docker compose up docs-dev-server

  # ===============================================================================================

  build:all:
    desc: 'Lint and build all container images'
    cmds:
      - for: ['devcontainer', 'folderslint', 'ftp-client', 'mkdocs']
        task: build:{{.ITEM}}

  build:*:
    desc: 'Lint and build container image | Replace * with image name'
    vars:
      IMAGE: '{{index .MATCH 0}}'
    cmds:
      - docker compose up {{.IMAGE}}-lint-dockerfile --exit-code-from {{.IMAGE}}-lint-dockerfile
      - docker compose build {{.IMAGE}}
