---
version: '3'
tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose up cleanup
      - docker compose down --remove-orphans

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for:
          matrix:
            LINTER: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{.ITEM.LINTER}}

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - docker compose up docs-dev-server

  build:devcontainer:
    desc: 'Lint and build the devcontainer image'
    cmds:
      - docker compose up devcontainer-lint-dockerfile
      - docker compose build devcontainer

  build:folderslint:
    desc: 'Lint and build the folderslint image'
    cmds:
      - docker compose up folderslint-lint-dockerfile
      - docker compose build folderslint

  build:ftp-client:
    desc: 'Lint and build the ftp-client image'
    cmds:
      - docker compose up ftp-client-lint-dockerfile
      - docker compose build ftp-client

  build:mkdocs:
    desc: 'Lint and build the mkdocs image'
    cmds:
      - docker compose up mkdocs-lint-dockerfile
      - docker compose build mkdocs
