---
version: '3.42.1'

vars:
  INSPEC_DIR: tests/inspec

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose up cleanup
      - docker compose down --remove-orphans
      - rm -rf .cache
      - rm -rf node_modules
      - rm -rf target

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for:
          matrix:
            LINTER: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links']
        cmd: docker compose up lint-{{.ITEM.LINTER}} --exit-code-from lint-{{.ITEM.LINTER}}

  inspec:check:all:
    desc: 'Vendor and check InSpec profile validity'
    cmds:
      - for: &test-inspec ['devcontainer', 'ftp-client']
        task: inspec:check:{{.ITEM}}

  inspec:check:*:
    desc: 'Vendor and check InSpec profile validity'
    vars:
      PROFILE: '{{index .MATCH 0}}'
    cmds:
      - rm -f "{{.INSPEC_DIR}}/{{.PROFILE}}/inspec.lock"
      - docker compose run --rm inspec vendor "{{.INSPEC_DIR}}/{{.PROFILE}}" --overwrite --chef-license=accept
      - docker compose run --rm inspec check "{{.INSPEC_DIR}}/{{.PROFILE}}" --chef-license=accept

  # ===============================================================================================

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - docker compose up docs-dev-server

  # ===============================================================================================

  build:all:
    desc: 'Lint and build all container images'
    cmds:
      - for: &images ['devcontainer', 'folderslint', 'ftp-client', 'mkdocs']
        task: build:{{.ITEM}}

  build:*:
    desc: 'Lint and build container image | Replace * with image name'
    vars:
      IMAGE: '{{index .MATCH 0}}'
    cmds:
      - docker compose up {{.IMAGE}}-lint-dockerfile --exit-code-from {{.IMAGE}}-lint-dockerfile
      - docker compose build {{.IMAGE}}

  # ===============================================================================================

  test:all:
    desc: 'Test all container images'
    cmds:
      - for: *test-inspec
        task: test:{{.ITEM}}

  test:*:
    desc: 'Test container image | Replace * with image name'
    vars:
      IMAGE: '{{index .MATCH 0}}'
    cmds:
      - docker run --name "system-under-test-{{.IMAGE}}" -d -v "$(pwd):$(pwd):ro" -w "$(pwd)" "local/{{.IMAGE}}:dev" sleep 180s
      - sleep 5
      - docker compose run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$(pwd):$(pwd)" -w "$(pwd)" inspec exec "{{.INSPEC_DIR}}/{{.IMAGE}}" --target "docker://system-under-test-{{.IMAGE}}" --no-distinct-exit --chef-license=accept
      - sleep 5
      - docker stop "system-under-test-{{.IMAGE}}"
      - docker rm "system-under-test-{{.IMAGE}}"
