FROM squidfunk/mkdocs-material:9.5.39
LABEL maintainer="sebastian@sommerfeld.io"
LABEL org.opencontainers.image.vendor="sommerfeld-io"
LABEL org.opencontainers.image.documentation="https://sommerfeld-io.github.io/container-images/images/mkdocs"

RUN pip install --no-cache-dir mkdocs-kroki-plugin==0.9.0
