---
name: "Scan"

on:
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch:

env:
  IMAGE_TAG_RC: rc
  IMAGE_TAG_LATEST: latest
  REGISTRY: docker.io
  DOCKER_SCOUT_REPO: devcontainer

permissions:
  contents: read
  security-events: write

jobs:

  scan-images:
    name: ${{ matrix.image-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: ['devcontainer', 'folderslint', 'ftp-client', 'mkdocs']
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "job_date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Docker Scout Action
        id: docker-scout-cves
        uses: docker/scout-action@v1.18.0
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
          sarif-file: sarif-output.json
          summary: false
      - name: Upload SARIF result
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-output.json
          category: 'Docker Scout'
      # - name: DEBUG
      #   run: |
      #     touch TEST.md
      #     pwd
      #     ls -alF
      #   shell: bash
      # - name: Create GitHub issue
      #   uses: peter-evans/create-issue-from-file@v5
      #   with:
      #     title: "Scan Report - ${{ steps.date.outputs.job_date }} - ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}"
      #     content-filepath: scout-report.md
      #     labels: security,docker
