---
name: "Scan Container Images"

on:
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch:

env:
  IMAGE_TAG_RC: rc
  IMAGE_TAG_LATEST: latest
  REGISTRY: docker.io
  DOCKER_SCOUT_REPO: devcontainer

permissions:
  contents: read
  security-events: write

jobs:

  docker-scout:
    name: ${{ matrix.image-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: ['devcontainer', 'folderslint', 'ftp-client', 'mkdocs']
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "job_date=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"
        shell: bash
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Scout - CVE Scan
        uses: docker/scout-action@v1.18.1
        with:
          command: cves
          image: ${{ env.REGISTRY }}/${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
          sarif-file: sarif-output.json
          summary: false
          organization: ${{ secrets.DOCKERHUB_USER }}
      - name: Upload SARIF result
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-output.json
          category: 'Docker Scout CVEs - ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}'
          checkout_path: components/${{ matrix.image-name }}
