---
name: "Scan"

on:
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch:

env:
  IMAGE_TAG_RC: rc
  IMAGE_TAG_LATEST: latest
  REGISTRY: docker.io
  DOCKER_SCOUT_REPO: devcontainer

permissions:
  contents: read

jobs:

  scan:
    name: Scan Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-name: ['devcontainer', 'folderslint', 'ftp-client', 'mkdocs']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh
        shell: bash
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        shell: bash
      - name: Create GitHub Issue with Scan Report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE: ${{ secrets.DOCKERHUB_USER }}/${{ matrix.image-name }}:${{ env.IMAGE_TAG_LATEST }}
          JOB_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          CVE=$(docker scout cves "$IMAGE" --format markdown || echo "No CVE data found")
          POLICY=$(docker scout policy "$IMAGE" --org sommerfeldio  || echo "No policy data found")

          DATE=$(date +'%Y-%m-%d')
          TITLE="Scan Report - $DATE - $IMAGE"
          LABELS="security"

          read -r -d '' BODY <<EOF
            | Image  | Job                                         |
            |--------|---------------------------------------------|
            | $IMAGE | [Scan Run ${{ github.run_id }}]($JOB_URL) |

            ---

            $CVE

            ---

            $POLICY
          EOF

          gh issue create --title "$TITLE" --label "$LABELS" --body "$BODY" --repo "${{ github.repository }}"
        shell: bash
